export const robotConfig = {
  name: "Wangpeng Proto",
  limits: {
    leftShoulderLift: { min: 15, max: 135, initial: 20, step: 2 },
    rightShoulderLift: { min: 15, max: 135, initial: 20, step: 2 },
    leftShoulderRotate: { min: -90, max: 90, initial: 0, step: 2 },
    rightShoulderRotate: { min: -90, max: 90, initial: 0, step: 2 },
    leftElbow: { min: 15, max: 135, initial: 30, step: 3 },
    rightElbow: { min: 15, max: 135, initial: 30, step: 3 },
    leftGripper: { min: 0, max: 45, initial: 20, step: 2 },
    rightGripper: { min: 0, max: 45, initial: 20, step: 2 },
  },
  keymap: {
    arrowup: { type: "base", action: "forward" },
    arrowleft: { type: "base", action: "turnLeft" },
    arrowright: { type: "base", action: "turnRight" },
    q: { type: "joint", targets: ["leftShoulderLift"], label: "????" },
    e: { type: "joint", targets: ["rightShoulderLift"], label: "????" },
    a: { type: "joint", targets: ["leftShoulderRotate"], label: "????" },
    d: { type: "joint", targets: ["rightShoulderRotate"], label: "????" },
    z: { type: "joint", targets: ["leftElbow"], label: "????" },
    c: { type: "joint", targets: ["rightElbow"], label: "????" },
    w: { type: "joint", targets: ["leftGripper"], label: "??????" },
    x: { type: "joint", targets: ["rightGripper"], label: "??????" },
    s: { type: "reset", holdMs: 3000, label: "??????" },
    shift: { type: "modifier", label: "???" },
  },
  instructions: [
    "??????????????",
    "Q / E??? / ??????? Shift ????",
    "A / D??? / ??????? Shift ????",
    "Z / C??? / ??????? Shift ????",
    "W / X??? / ????????? Shift ????",
    "S??? 3 ????????????",
  ],
};
